#!/usr/bin/env bash

DESCRIPTIONS_PATH=$(dirname "$(realpath $0)")/descriptions

mkdir -p $DESCRIPTIONS_PATH
cd $DESCRIPTIONS_PATH


#git clone https://github.com/AoyunTech/ayspot_a0_description
git clone https://github.com/AoyunTech/ayspot_a1_description
