left_front:
  - LF_HIP_rotate
  - LF_THIGH_roate
  - LF_SHARK_rotate
  - LF_FOOT_rigid

right_front:
  - RF_HIP_rorate
  - RF_THIGH_rotate
  - RF_SHARK_rotate
  - RF_FOOT_rigid

left_hind:
  - LH_HIP_rotate
  - LH_THIGH_rotate
  - LH_SHARK_rotate
  - LH_FOOT_rigid

right_hind:
  - RH_HIP_rotate
  - RH_THIGH_rotate
  - RH_SHARK_rotate
  - RH_FOOT_rigid